print ("modificacion anterior")
print("actualizacion de moises")
print ("modificacion anterior")
print("actualizacion de moises")print ("modificacion anterior")
print("actualizacion de moises")
print ("modificacion anterior")
print("actualizacion de moises")print ("modificacion anterior")
print("actualizacion de moises")print ("modificacion anterior")
print("actualizacion de moises")print ("modificacion anterior")
print("actualizacion de moises")print ("modificacion anterior")
print("actualizacion de moises")print ("modificacion anterior")
print("actualizacion de moises")